version: '3'
services:
#  web:
#    build: ./
#    image: seckill
#    container_name: docker_seckill
#    command: ./seckill
#    restart: always
#    ports:
#      - "8000:8000"
#    volumes:
#      - "$HOME/docker/seckill:/app/seckill"
#    networks:
#      - net-seckill
#    depends_on:
#      - mysql-master
#      - mysql-slave
#      - redis


  redis:
    image: redis:4.0-alpine
    container_name: docker_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "$HOME/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "$HOME/docker/redis/data:/data"
    networks:
      - net-seckill

  mysql-master:
    image: mysql:5.7.30
    container_name: docker_mysql_master
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-time-zone=+8:00
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: seckill
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - "$HOME/docker/mysql_master/data:/var/lib/mysql"
      - "$HOME/docker/mysql_master/conf/my.cnf:/etc/mysql/my.cnf"
    networks:
      - net-seckill

  mysql-slave:
    image: mysql:5.7.30
    container_name: docker_mysql_slave
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-time-zone=+8:00
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: seckill
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_USER: test   #创建test用户
      MYSQL_PASSWORD: test  #设置test用户的密码
    restart: always
    ports:
      - "13307:3306"
    volumes:
      - "$HOME/docker/mysql_slave/data:/var/lib/mysql"
      - "$HOME/docker/mysql_slave/conf/my.cnf:/etc/mysql/my.cnf"
    networks:
      - net-seckill

  rabbitMQ:
    image: rabbitmq:3.7.8-management
    hostname: rabbit1
    container_name: docker_rabbitmq
    #总是重启后启动
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "$HOME/docker/rabbitmq/data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      - net-seckill


networks:
  net-seckill:
    driver: bridge