definitions:
  model.User:
    properties:
      head:
        type: string
      last_login_date:
        type: string
      login_count:
        type: integer
      nickname:
        type: string
      password:
        type: string
      phone:
        type: string
      salt:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /base/register:
    post:
      parameters:
      - description: 用户注册接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 用户注册账号
      tags:
      - Base
  /fileUploadAndDownload/breakpointContinue:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: an example for breakpoint resume, 断点续传示例
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"上传成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 测试链接到服务器
      tags:
      - ExaFileUploadAndDownload
swagger: "2.0"
